"""Static HTML template structure for analysis reports."""

PREACT_CDN = '''
<script type="module">
import { h, render } from 'https://esm.sh/preact@10.19.3';
import { useState, useEffect, useCallback, useMemo } from 'https://esm.sh/preact@10.19.3/hooks';
import htm from 'https://esm.sh/htm@3.1.1';
const html = htm.bind(h);
window.h = h;
window.render = render;
window.useState = useState;
window.useEffect = useEffect;
window.useCallback = useCallback;
window.useMemo = useMemo;
window.html = html;
</script>
'''


def generate_html_shell(
    page_title: str,
    favicon_link: str,
    css: str,
    summary_comment: str,
    static_content: str,
    app_data_json: str,
    app_js: str,
) -> str:
    """Generate the complete HTML document shell.

    Args:
        page_title: Title for the browser tab
        favicon_link: HTML for favicon link tag
        css: Complete CSS styles
        summary_comment: HTML comment with summary markdown (for IDE viewing)
        static_content: Static HTML sections (header, charts, etc.)
        app_data_json: JSON string with app data for Preact
        app_js: Preact application JavaScript code

    Returns:
        Complete HTML document as string
    """
    return f'''{summary_comment}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{page_title}</title>
    {favicon_link}
    <style>
{css}
    </style>
</head>
<body>
    <div class="container">
        {static_content}

        <!-- Preact App Mount Point -->
        <div id="grades-app-mount"></div>

        <footer>
            Generated by c - EGF Analysis CLI
        </footer>
    </div>

    <!-- Preact + htm from CDN -->
    {PREACT_CDN}

    <!-- App Data -->
    <script id="appData" type="application/json">
{app_data_json}
    </script>

    <!-- Preact App -->
    <script type="module">
{app_js}
    </script>
</body>
</html>'''
